### Ручное управление циклом событий
```
    До сих пор мы пользовались вспомогательной функцией asyncio.run, 
    которая за кулисами создавала цикл событий и запускала приложение. 
```

### Создание цикла событий вручную
```
    Мы можем создать цикл событий, воспользовавшись методом asyncio.new_event_loop. 
    Он возвращает экземпляр цикла событий, который дает доступ ко всем низкоуровневым методам, 
    в частности методу run_until_complete, который принимает сопрограмму и исполняет ее до завершения. 
    Закончив работу с циклом событий, мы должны закрыть его, чтобы освободить занятые ресурсы. 
    Обычно это делается в блоке finally, чтобы цикл был закрыт даже в случае исключения. 
```

### Получение доступа к циклу событий
```
   Иногда бывает необходим доступ к текущему циклу событий. 
   Библиотека asyncio предоставляет для этой цели функцию asyncio.get_running_loop. 
   
   Существует еще функция asyncio.get_event_loop, также позволяющая получить доступ к циклу событий. 
   Эта функция может создать новый цикл событий, если его еще не существует в момент вызова, что ведет 
   к  странному поведению. Рекомендуется использовать get_running_loop, поскольку она возбуждает исключение, 
   если цикл событий не запущен, что позволяет избежать сюрпризов.
```

### Отладочный режим
```
    Любую сопрограмму всегда следует ожидать в какой-то точке приложения. 
    
    1 - asyncio.run(coroutine(), debug=True)
    2 - python3 -X dev program.py
    3 - PYTHONASYINCIODEBUG=1 python3 program.py

```